version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    python:
      patterns:
      - "*"
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    ruby:
      patterns:
      - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    actions:
      patterns:
      - "*"
