name: Deploy on Cloudflare Pages (Production)

on:
  repository_dispatch:
    types:
    - publish_latest_tag

concurrency: cfp-production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Trigger deploy hook
      run: |
        curl -X POST ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_HOOK_PRODUCTION }}
