name: Publish

on:
  workflow_run:
    workflows:
    - Build
    types:
    - completed

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Create deployment
      id: deployment
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        https://api.github.com/repos/${{ github.repository }}/deployments \
        -d '{"ref":"${{ github.event.workflow_run.head_sha }}","environment":"${{ github.event.workflow_run.event == 'push' && 'Production' || 'Preview' }}","required_contexts":[]}' \
        | jq --raw-output0 '"url=\(.statuses_url)"' >> $GITHUB_OUTPUT

    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{github.event.workflow_run.id }}

    - name: Get branch name
      id: branch
      run: |
        echo "name=$(cat branch/name)" >> $GITHUB_OUTPUT

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      id: pages
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy _site --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch ${{ steps.branch.outputs.name }}

    - name: Update deployment
      if: always()
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        ${{ steps.deployment.outputs.url }} \
        -d '{"state":"${{ job.status }}","log_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","environment_url":"${{ steps.pages.outputs.pages-deployment-alias-url }}","auto_inactive":false}'
