name: Publish

on:
  workflow_run:
    workflows:
    - Build
    types:
    - completed

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    environment:
      name: ${{ github.event.workflow_run.event == 'push' && 'Production' || 'Preview' }}
      url: ${{ steps.pages.outputs.pages-deployment-alias-url }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{github.event.workflow_run.id }}

    - name: Get branch name
      id: branch
      run: |
        echo "name=$(cat branch/name)" >> $GITHUB_OUTPUT

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      id: pages
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy _site --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch ${{ steps.branch.outputs.name }}
