name: New Release

on:
  release:
    types: [published]

jobs:
  new_release:
    name: New Release
    runs-on: ubuntu-latest

    steps:
    - name: Get SHA of tag
      id: tag_sha
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/{repository}/commits/{tag}?per_page=1
        repository: ${{ github.repository }}
        tag: ${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy main branch to production branch
      uses: octokit/request-action@v2.x
      with:
        route: PATCH /repos/{repository}/git/refs/heads/production
        repository: ${{ github.repository }}
        sha: ${{ fromJson(steps.tag_sha.outputs.data).sha }}
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
